name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - bokeh
  - rise
  - pip:
    - jupyter-contrib-nbextensions
    - jupyter-nbextensions-configurator
